name: mimic
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python
  - pytorch
  - scikit-learn
  - scipy
  - tensorboardx
  - tensorflow
  - torchvision
  - tqdm
  - imageio
  - nltk
  - libgcc
