#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# check if the module command exists (only on the cluster)
if command -v module &> /dev/null; then
    echo "Loading Modules..."
    module load cuda/10.0.130
    module load cudnn/7.5
    module load openblas/0.2.19
fi

# define TMPDIR, if it's empty
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi
echo "TMPDIR: $TMPDIR"

# activate conda env
eval "$(conda shell.bash hook)"
conda activate joint-elbo
echo "CONDA_PREFIX: $CONDA_PREFIX"

# set constants
DEBUG=false
LOGDIR=""
METHOD="moe"
LIKELIHOOD="laplace"
DIR_DATA="$PWD/data"
DIR_CLF="$PWD/trained_classifiers/MMNIST"
DIR_EXPERIMENT_BASE="$PWD"
DIR_EXPERIMENT="$PWD/runs"  # NOTE: experiment logs are written here
PATH_INC_V3="$PWD/pt_inception-2015-12-05-6726825d.pth"
DIR_FID="$TMPDIR/MMNIST"

# copy data to TMPDIR, if the data does not already lie there
if [ ! -d "$TMPDIR/MMNIST" ]; then
    cp -r "${DIR_DATA}/MMNIST" "${TMPDIR}/"
fi
# cp -r "${DIR_DATA}/SVHN" "${TMPDIR}/"
# cp -r "${DIR_DATA}/MNISTSVHN" "${TMPDIR}/"

ipython main_mmnist.py -- \
            --unimodal-datapaths-train "$TMPDIR/MMNIST/train/m"{0..4} \
            --unimodal-datapaths-test "$TMPDIR/MMNIST/test/m"{0..4} \
			--dir_clf="$DIR_CLF" \
			--dir_experiment="$DIR_EXPERIMENT" \
			--inception_state_dict="$PATH_INC_V3" \
			--dir_fid="$DIR_FID" \
			--method=$METHOD \
			--style_dim=0 \
			--class_dim=20 \
			--beta=2.5 \
			--likelihood=$LIKELIHOOD \
			--batch_size=256 \
			--initial_learning_rate=0.0005 \
			--eval_freq=10 \
			--eval_freq_fid=10 \
			--data_multiplications=20 \
			--num_hidden_layers=1 \
			--end_epoch=200 \

# NOTE: I use equal weighting of the following div_weights by 1 / (num_mods + 1)
# --div_weight_m1_content=0.25 \
# --div_weight_uniform_content=0.25 \
            
