#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# check if the module command exists (only on the cluster)
if command -v module &> /dev/null; then
    echo "Loading Modules..."
    module load cuda/10.0.130
    module load cudnn/7.5
    module load openblas/0.2.19
fi

# define TMPDIR, if it's empty
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi
echo "TMPDIR: $TMPDIR"

# activate conda env
eval "$(conda shell.bash hook)"
conda activate joint-elbo
echo "CONDA_PREFIX: $CONDA_PREFIX"

# set constants
DEBUG=false
LOGDIR=""
METHOD="moe"
LIKELIHOOD_M1="laplace"
LIKELIHOOD_M2="laplace"
LIKELIHOOD_M3="categorical"
DIR_DATA="$PWD/data"
DIR_CLF="$PWD/trained_classifiers/MNISTSVHN"
DIR_EXPERIMENT_BASE="$PWD"
DIR_EXPERIMENT="$PWD/runs"  # NOTE: experiment logs are written here
PATH_INC_V3="$PWD/pt_inception-2015-12-05-6726825d.pth"
DIR_FID="$TMPDIR/MNIST_SVHN_text"

# copy data to TMPDIR
cp -r "${DIR_DATA}/MNIST" "${TMPDIR}/"
cp -r "${DIR_DATA}/SVHN" "${TMPDIR}/"
cp -r "${DIR_DATA}/MNISTSVHN" "${TMPDIR}/"


python main_svhnmnist.py --dir_data="$TMPDIR" \
			--dir_clf="$DIR_CLF" \
			--dir_experiment="$DIR_EXPERIMENT" \
			--inception_state_dict="$PATH_INC_V3" \
			--dir_fid="$DIR_FID" \
			--method=$METHOD \
			--style_m1_dim=0 \
			--style_m2_dim=0 \
			--style_m3_dim=0 \
			--class_dim=20 \
			--beta=2.5 \
			--div_weight_m1_content=0.25 \
			--div_weight_m2_content=0.25 \
			--div_weight_m3_content=0.25 \
			--div_weight_uniform_content=0.25 \
			--likelihood_m1=$LIKELIHOOD_M1 \
			--likelihood_m2=$LIKELIHOOD_M2 \
			--likelihood_m3=$LIKELIHOOD_M3 \
			--batch_size=256 \
			--initial_learning_rate=0.0005 \
			--eval_freq=10 \
			--eval_freq_fid=10 \
			--data_multiplications=20 \
			--num_hidden_layers=1 \
			--end_epoch=200 \
